#!/usr/bin/env bash


clues="$(grep 'CLUE:' crimescene)"

target_memberships="$(grep 'CLUE:' crimescene |\
grep 'card' |\
sed 's/^.*cards for //; s/\..*$//' |\
sed 's/, /\n/g' |\
sed 's/ /_/g' |\
sed '/^the/ c Terminal_City_Library' |\
sed 's/and_the_//')"

process_membership() {
    pushd 2>&1 >/dev/null memberships
    sort "$1" -o "$1"
    popd  2>&1 >/dev/null
}

while IFS= read -r line; do
    process_membership "$line"
done <<< "$target_memberships"

mapfile -t memfiles <<< "$target_memberships"
pushd 2>&1 >/dev/null memberships
raw_possible="$(awk -F$'\n' '
{
    seen_count[$1]++;
}
END {
    for (name in seen_count)
    {
        if (seen_count[name] >= ARGC - 1)
        {
            print name;
        }
    }
}
' "${memfiles[@]}")"
popd  2>&1 >/dev/null



git add .
git commit -m 'maybe progress?'
git push

exit 0

possible="$(sort <<< $raw_possible)"
while IFS= read -r name; do
    echo "$name"
    pushd 2>&1 >/dev/null interviews

    for file in ./*; do
        head "$file"
        #grep -F -- "$name" "$file"
    done

    popd 2>&1 >/dev/null
done <<<"$possible"
exit 0

echo "$clues"
ls -la
